version: "3.8"
services: 
  mongodb:
    image: 'mongo:3.6.22-xenial'
    volumes: 
      - data:/data/db
    #environment: 
    #  MONGO_INITDB_ROOT_USERNAME: max
    #  MONGO_INITDB_ROOT_PASSWORD: secret
    env_file: 
      - ./env/mongo.env
    #networks: 
    #  - goals-net
  backend:
    build: ./backend
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    ports: 
      - '3000:80'
    volumes: 
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on: 
      - mongodb
  frontend:
    build: ./frontend
    ports: 
      - '3001:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend
volumes: 
  data:
  logs:
